Hotfix animal emblem ranks
cipherxof/mgo2pc-frontend pull request #5
Opened 2023-02-15 23:40 UTC by LeroyAndrade

+ animal emblems shown
+ animal title shown

2023-02-17 18:20 UTC, cipherxof requested changes
In general, I would remove all of your changes except for where you added the ID to the rank images. From there, I'll store the images on the server using the ID which is the simplest solution.

2023-02-17 18:20 UTC, cipherxof commented on src/system/utility.tsx
> +export const arrayAnimalRanks = [
We don't really need a lookup table for the rank images. I'll just store the ranks on the server using the ID instead.

2023-02-17 18:20 UTC, cipherxof commented on src/pages/RankGuide.tsx
> +// for (const rank of ranks) {
Remove all of the unused code.

2023-02-17 18:20 UTC, cipherxof commented on src/pages/RankGuide.tsx
> +  const pathToImg = `https://mgo2pc.com/static/media/emblem/${arrayAnimalRanks[countArrayAnimalRanks][1]}.png`;
This variable is unused.

2023-02-17 18:20 UTC, cipherxof commented on src/pages/RankGuide.tsx
> +import { Card, Descriptions, Typography } from 'antd';
Remove unused imports.

2023-02-17 18:20 UTC, cipherxof commented on src/pages/RankGuide.tsx
> +import {useState}  from 'react';
unused

2023-02-17 18:20 UTC, cipherxof commented on src/system/utility.tsx
> +  return `https://mgo2pc.com/static/media/emblem/${rank}.png`;
should be using relative paths

2023-03-09 16:39 UTC, LeroyAndrade commented
Thank you for the feedback.
As of now only the variable containing the absolute path should be edited to the relative path (RankGuide.tsx -> variable: pathToImgAndShowRankEmblem on line #493.
Other then that, all of your requests have been honored and executed.

2023-03-29 03:25 UTC, cipherxof commented
Seems good 👍

2023-03-29 03:25 UTC, merged